### ISSUE TITLE
When relaunch script, not trying to reimport failed URL

### ISSUE THREAD

**Issue by nicosomb** [wallabag/framabag-reimport-entries#3]
If I launch this tool many times, it tries to reimport URL who failed. Maybe check in log file if the URL fails. If not, fetch it.

**Comment by tcitworld** [comment]
But maybe it failed because the website is offline for a moment or something.

**Comment by nicosomb** [comment]
Maybe have a look at the date of the last try. If last try - current time < 5 min, then don't retry.

**Comment by tcitworld** [comment]
:+1:
